// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FinalDataBaseV20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalDataBaseV20));
        
        string IMigrationMetadata.Id
        {
            get { return "202112151621255_FinalDataBaseV2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
